---
- name: Retrieve log files
  hosts: "{{ target_hosts }}"
  gather_facts: no
  become: true
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  vars:
    pattern:
    - { dir: '/tmp/apigee', pattern: '*' }
    - { dir: '/tmp/edge', pattern: '*' }
    - { dir: '/tmp', pattern: 'setup*.log' }
    - { dir: '/etc/', pattern: 'hosts*' }
    - { dir: '/etc/', pattern: 'environment' }
    - { dir: '/etc/', pattern: 'profile' }
    - { dir: '/etc/', pattern: 'bashrc' }
    - { dir: '/etc/', pattern: 'resolv.conf' }
    - { dir: '/etc/', pattern: 'sysctl.conf' }
    - { dir: '/etc/', pattern: 'sudoers' }
    - { dir: '/etc/security/', pattern: 'limits.conf' }
    - { dir: '/etc/security/limits.d/', pattern: '*conf' }
    - { dir: '/var/log/', pattern: 'messages' }
    - { dir: '{{ opdk_installer_path }}/', pattern: '*.log' }
    - { dir: '{{ opdk_installer_path }}/', pattern: '*.txt' }
    - { dir: '{{ apigee_home }}/', pattern: '*.out' }
    - { dir: '{{ apigee_home }}/var/log', pattern: '*.log' }
    - { dir: '{{ opdk_installer_path }}/', pattern: '*.conf' }
    - { dir: '{{ opdk_installer_path }}/', pattern: '*.sh' }
    - { dir: '{{ apigee_home }}/customer/', pattern: '*' }
    - { dir: '{{ apigee_home }}/etc/', pattern: 'default*.sh' }
    - { dir: '{{ apigee_home }}/customer', pattern: '*' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*conf' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*cfg' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*yml' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*yaml' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*properties' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*conf' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*cfg' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*yml' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*yaml' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*properties' }
    - { dir: '{{ apigee_home }}/apigee-postgresql/', pattern: '*conf' }

  pre_tasks:
  - name: Create folder if missing
    delegate_to: 127.0.0.1
    become: no
    file:
      path: "{{ target_logs_folder }}"
      state: directory

  roles:
  - { role: apigee-fetch-files, download_pattern: '{{ pattern }}', download_folder: "{{ target_logs_folder }}" }
