---
- name: Update apigee-pre-req for the planet
  hosts: planet
  become_flags: beroot
  gather_facts: no
  strategy: free
  tags: ['apigee-pre-req']
  roles:
  - { role: apigee-opdk-setup-java-home, tags: ['java_home'] }
  - { role: apigee-opdk-temporary-remove-targets, tags: ['remove-targets'], when: temporary_move is defined }
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-bootstrap'] }
  - { role: apigee-opdk-temporary-restore-targets, tags: ['restore-targets'], when: temporary_move is defined }
  - { role: apigee-opdk-setup-silent-installation-config, tags: ['apigee-silent-config'] }
