---
- name: Update nodes with common OS pre-requisites
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['os-pre-req']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  vars:
    http_proxy: http://proxy.ebiz.verizon.com:80
    https_proxy: http://proxy.ebiz.verizon.com:80
    no_proxy: "10.118.70.177,oneartifactory.verizon.com,luxfavlpa001.verizon.com,luxsc1lna001.itcent.ebiz.verizon.com,10.118.68.8,localhost,127.0.0.1"
    artifactory_repo:
    - { name: "Artifactory",
        baseurl: "https://oneartifactory.verizon.com/artifactory/dl-fedoraproject-org-epel7-x86_64/",
        repo_id: "Artifactory",
        yum_repo_filename: "artifactory",
        gpgcheck: 'no'}
    yum_repositories:
    - { name: "Red Hat Enterprise Linux 7 Server (RPMs)",
        baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-rpms/Packages",
        repo_id: "rhel-7-server-rpms",
        yum_repo_filename: "{{ yum_repo_filename }}",
        gpgcheck: 'no'}
    - { name: "Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server",
        baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-server-rhscl-7-rpms/Packages",
        repo_id: "rhel-server-rhscl-7-rpms",
        yum_repo_filename: "{{ yum_repo_filename }}",
        gpgcheck: 'no'}
    - { name: "Red Hat Satellite Tools 6.2 (for RHEL 7 Server) (RPMs)",
        baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-satellite-tools-6.2-rpms/Packages",
        repo_id: "rhel-7-server-satellite-tools-6.2-rpms",
        yum_repo_filename: "{{ yum_repo_filename }}",
        gpgcheck: 'no'}
    - { name: "Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)",
        baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-supplementary-rpms/Packages",
        repo_id: "rhel-7-server-supplementary-rpms",
        yum_repo_filename: "{{ yum_repo_filename }}",
        gpgcheck: 'no'}
    - { name: "Red Hat Enterprise Linux 7 Server - RH Common (RPMs)",
        baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-rh-common-rpms/Packages",
        repo_id: "rhel-7-server-rh-common-rpms",
        yum_repo_filename: "{{ yum_repo_filename }}",
        gpgcheck: 'no'}
    - { name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)",
        baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-extras-rpms/Packages",
        repo_id: "rhel-7-server-extras-rpms",
        yum_repo_filename: "{{ yum_repo_filename }}",
        gpgcheck: 'no'}
    - { name: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)",
        baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-optional-rpms/Packages",
        repo_id: "rhel-7-server-optional-rpms",
        yum_repo_filename: "{{ yum_repo_filename }}",
        gpgcheck: 'no'}
  roles:
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository'], yum_repositories_enabled: true, yum_repo_filename: 'vz-aws-rhel7' }
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository','artifactory'], yum_repositories_enabled: true, yum_repo_filename: 'artifactory', yum_repositories: "{{ artifactory_repo }}" }
  - { role: apigee-opdk-setup-os-minimum, tags: ['os-minimum'] }
  - { role: apigee-server-restart, tags: ['server-restart'] }
  - { role: apigee-opdk-setup-os-limits, tags: ['apigee-tuning'] }
  - { role: apigee-opdk-setup-selinux-disable, tags: ['selinux'] }
  - { role: apigee-opdk-shutdown-iptables, tags: ['iptables'] }
  - { role: apigee-server-restart, tags: ['restart-server'], when: (selinux_disabled is defined and not selinux_disabled) or (iptables_disabled is defined and not iptables_disabled) }
  - { role: apigee-opdk-setup-os-common, tags: ['os-common'] }
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository', 'os-common'], yum_repositories_enabled: false, yum_repo_filename: 'vz-aws-rhel7' }
  - { role: apigee-opdk-setup-openjdk, tags: ['openjdk'], jdk_version: '1.8' }

- name: Update Postgres master nodes with OS pre-requisites
  hosts: pg
  gather_facts: no
  vars:
    - http_proxy: http://proxy.ebiz.verizon.com:80
    - https_proxy: http://proxy.ebiz.verizon.com:80
    - no_proxy: "10.118.70.177,oneartifactory.verizon.com,luxfavlpa001.verizon.com,luxsc1lna001.itcent.ebiz.verizon.com,10.118.68.8,localhost,127.0.0.1"
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  tags: ['os-pre-req', 'pg-os-pre-req']
  roles:
  - { role: apigee-opdk-setup-os-postgres, tags: ['os-pre-req'] }
  - { role: apigee-opdk-setup-postgres-config, tags: ['os-pre-req'] }

- name: Update Postgres standby nodes with OS pre-requisites
  hosts: pgstandby
  gather_facts: no
  vars:
    - http_proxy: http://proxy.ebiz.verizon.com:80
    - https_proxy: http://proxy.ebiz.verizon.com:80
    - no_proxy: "10.118.70.177,oneartifactory.verizon.com,luxfavlpa001.verizon.com,luxsc1lna001.itcent.ebiz.verizon.com,10.118.68.8,localhost,127.0.0.1"
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  tags: ['os-pre-req', 'pg-os-pre-req']
  roles:
  - { role: apigee-opdk-setup-os-postgres, tags: ['os-pre-req'] }
  - { role: apigee-opdk-setup-postgres-config, tags: ['os-pre-req'], clear_pgdata: True }
