---
- name: Update apigee-pre-req for the planet
  hosts: "{{ target_hosts }}"
  gather_facts: no
  strategy: free
  tags: ['apigee-config']
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, tags: ['apigee-silent-config'] }
