---
- name: Update common components for the planet
  hosts: "{{ target_hosts }}"
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  strategy: free
  tags: ['common']
  roles:
  - { role: apigee-opdk-update-component-inplace, component: 'apigee-setup', tags: ['setup', 'apigee-component-update'] }
  - { role: apigee-opdk-update-component-inplace, component: 'apigee-adminapi', tags: ['adminapi', 'apigee-component-update'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user','ownership'] }

- name: Update management server components
  hosts: "{{ target_hosts }}"
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  strategy: free
  tags: ['common']
  roles:
  - { role: apigee-opdk-update-component-inplace, component: 'apigee-validate', tags: ['validate', 'apigee-component-update'] }
  - { role: apigee-opdk-update-component-inplace, component: 'apigee-provision', tags: ['provision', 'apigee-component-update'] }
