---
- name: Update apigee-pre-req for the planet
  hosts: "{{ target_hosts }}"
  gather_facts: no
  strategy: free
  tags: ['apigee-pre-req']
  roles:
  - { role: apigee-opdk-setup-java-home, tags: ['java_home'] }
  - { role: apigee-opdk-temporary-remove-targets, tags: ['remove-targets'], when: temporary_move is defined }
  - { role: apigee-opdk-yum-repository-proxy-config, yum_repo_filename: 'vz-aws-rhel7', when: https_proxy is defined }
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository','vz-aws_rhel7'], yum_repositories_enabled: true, yum_repo_filename: 'vz-aws-rhel7' }
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-bootstrap'], http_proxy: None, https_proxy: None, no_proxy: None }
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository'], yum_repositories_enabled: true, yum_repo_filename: 'vz-aws-rhel7' }
  - { role: apigee-opdk-temporary-restore-targets, tags: ['restore-targets'], when: temporary_move is defined }
