---
- name: Update nodes with common OS pre-requisites
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['os-pre-req']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-epel, tags: ['epel'] }
  - { role: apigee-opdk-setup-os-minimum, tags: ['os-minimum'] }
  - { role: apigee-opdk-setup-os-limits, tags: ['apigee-tuning'] }
  - { role: apigee-opdk-setup-selinux-disable, tags: ['selinux'] }
  - { role: apigee-opdk-shutdown-iptables, tags: ['iptables'] }
  - { role: apigee-server-restart, tags: ['restart-server'], when: (selinux_disabled.changed is defined and selinux_disabled.changed) or (iptables_disabled is defined and not iptables_disabled) or (force_restart is defined and force_restart)  }
  - { role: apigee-opdk-setup-os-common, tags: ['os-common'] }
  - { role: apigee-opdk-setup-openjdk, tags: ['openjdk'], jdk_version: '1.8' }

- name: Update Postgres master nodes with OS pre-requisites
  hosts: pg
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  tags: ['os-pre-req', 'pg-os-pre-req']
  roles:
  - { role: apigee-opdk-setup-os-postgres, tags: ['os-pre-req'] }
  - { role: apigee-opdk-setup-postgres-config, tags: ['os-pre-req'] }

- name: Update Postgres standby nodes with OS pre-requisites
  hosts: pgstandby
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  tags: ['os-pre-req', 'pg-os-pre-req']
  roles:
  - { role: apigee-opdk-setup-os-postgres, tags: ['os-pre-req'] }
  - { role: apigee-opdk-setup-postgres-config, tags: ['os-pre-req'], clear_pgdata: True }
