---
- name: Update nodes with common OS pre-requisites
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['os-pre-req']
  vars:
    artifactory_repo:
    - { name: "Artifactory",
        baseurl: "https://oneartifactory.verizon.com/artifactory/dl-fedoraproject-org-epel7-x86_64/",
        repo_id: "Artifactory",
        yum_repo_filename: "artifactory",
        gpgcheck: 'no'}
  roles:
  - { role: apigee-opdk-ssh-user, tags: ['root'], user: 'root' }
  - { role: apigee-opdk-temporary-remove-targets, tags: ['remove-targets','os-minimum'], when: temporary_move is defined }
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository'], yum_repositories_enabled: true, yum_repo_filename: 'vz-aws-rhel7' }
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository','artifactory'], yum_repositories_enabled: true, yum_repo_filename: 'artifactory', yum_repositories: "{{ artifactory_repo }}" }
  - { role: apigee-opdk-setup-os-minimum, tags: ['os-minimum'] }
  - { role: apigee-opdk-temporary-restore-targets, tags: ['restore-targets','os-minimum'], when: temporary_move is defined }
  - { role: apigee-opdk-setup-apigee-user, tags: ['apigee-user'] }
  - { role: apigee-opdk-setup-target-links, tags: ['links'], when: target_links is defined }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user','apigee-user-ownership'] }
  - { role: apigee-opdk-setup-os-limits, tags: ['apigee-tuning'] }
  - { role: apigee-opdk-setup-selinux-disable, tags: ['selinux'] }
  - { role: apigee-opdk-shutdown-iptables, tags: ['iptables'] }
  - { role: apigee-server-restart, tags: ['restart-server'], when: (selinux_disabled is defined and not selinux_disabled) or (iptables_disabled is defined and not iptables_disabled) }
  - { role: apigee-opdk-temporary-remove-targets, tags: ['remove-targets','os-common'], when: temporary_move is defined }
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository', 'os-common'], yum_repositories_enabled: true, yum_repo_filename: 'vz-aws-rhel7' }
  - { role: apigee-opdk-setup-os-common, tags: ['os-common'] }
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository', 'os-common'], yum_repositories_enabled: false, yum_repo_filename: 'vz-aws-rhel7' }
  - { role: apigee-opdk-temporary-restore-targets, tags: ['restore-targets','os-common'], when: temporary_move is defined }
  - { role: apigee-opdk-setup-openjdk, tags: ['openjdk'], jdk_version: '1.8' }

- name: Update Postgres master nodes with OS pre-requisites
  hosts: pg
  gather_facts: no
  tags: ['os-pre-req', 'pg-os-pre-req']
  roles:
  - { role: apigee-opdk-enable-swap, tags: ['os-pre-req','pg-swap-file'] }
  - { role: apigee-opdk-setup-os-postgres, tags: ['os-pre-req'] }
  - { role: apigee-opdk-setup-postgres-config, tags: ['os-pre-req'] }

- name: Update Postgres standby nodes with OS pre-requisites
  hosts: pgstandby
  gather_facts: no
  tags: ['os-pre-req', 'pg-os-pre-req']
  roles:
  - { role: apigee-opdk-enable-swap, tags: ['os-pre-req','pg-swap-file'] }
  - { role: apigee-opdk-setup-os-postgres, tags: ['os-pre-req'] }
  - { role: apigee-opdk-setup-postgres-config, tags: ['os-pre-req'], clear_pgdata: True }
