---
- name: Update Postgres master nodes with OS pre-requisites
  hosts: pg
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  tags: ['os-pre-req', 'pg-os-pre-req']
  roles:
  - { role: apigee-opdk-setup-os-postgres, tags: ['os-pre-req'] }
  - { role: apigee-opdk-setup-postgres-config, tags: ['os-pre-req'] }

- name: Update Postgres standby nodes with OS pre-requisites
  hosts: pgstandby
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  tags: ['os-pre-req', 'pg-os-pre-req']
  roles:
  - { role: apigee-opdk-setup-os-postgres, tags: ['os-pre-req'] }
  - { role: apigee-opdk-setup-postgres-config, tags: ['os-pre-req'], clear_pgdata: True }
