---
- name: Update apigee-pre-req for the planet
  hosts: "{{ target_hosts }}"
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  strategy: free
  tags: ['apigee-pre-req']
  roles:
  - { role: apigee-opdk-setup-apigee-user, tags: ['apigee-user'] }
  - { role: apigee-opdk-setup-target-links, tags: ['links'], when: target_links is defined }
  - { role: apigee-opdk-setup-java-home, tags: ['java_home'] }
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-bootstrap'] }
#  - { role: apigee-opdk-setup-component-install, component: 'apigee-attribution', tags: ['apigee-component'] }
#  - { role: apigee-opdk-setup-component-install, component: 'apigee-lib', tags: ['apigee-component'] }
#  - { role: apigee-opdk-setup-component-install, component: 'apigee-configutil', tags: ['apigee-component'] }
  - { role: apigee-opdk-setup-component-install, component: 'apigee-setup', tags: ['apigee-component'] }
  - { role: apigee-opdk-setup-component-install, component: 'apigee-adminapi', tags: ['apigee-component'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user','apigee-user-ownership'] }
