---
- name: Update apigee-pre-req for the planet
  hosts: "{{ target_hosts }}"
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  strategy: free
  tags: ['apigee-pre-req']
  roles:
  - { role: apigee-opdk-setup-java-home, tags: ['java_home'] }
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-bootstrap'] }
