---
- name: Install common components for the planet
  hosts: "{{ target_hosts }}"
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  strategy: free
  tags: ['apigee-pre-req','common-install']
  pre_tasks:
  - name: Clear errors with host status
    meta: clear_host_errors

  roles:
  - { role: apigee-opdk-setup-component-install, component: 'apigee-setup', tags: ['setup', 'apigee-component-install'] }
  - { role: apigee-opdk-setup-component-install, component: 'apigee-adminapi', tags: ['adminapi', 'apigee-component-install'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user','ownership'] }
