---
- name: Update openldap node
  hosts: ldap
  gather_facts: no
  tags: ['os-pre-req','openldap']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-os-openldap, tags: ['openldap'] }
