---
- name: Update apigee-pre-req for the planet
  hosts: planet
  gather_facts: no
  strategy: free
  tags: ['apigee-pre-req']
  vars:
    yum_os_packages:
    - openldap-servers
  roles:
  - { role: apigee-opdk-setup-java-home, tags: ['java_home'] }
  - { role: apigee-opdk-temporary-remove-targets, tags: ['remove-targets'], when: temporary_move is defined }
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository','vz-aws_rhel7'], yum_repositories_enabled: true, yum_repo_filename: 'vz-aws-rhel7' }
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-bootstrap'] }
  - { role: apigee-opdk-yum-packages, tags: ['yum-packages'], yum_os_packages: "{{ yum_os_packages}}" }
  - { role: apigee-opdk-yum-repository-enabled, tags: ['yum-repository'], yum_repositories_enabled: true, yum_repo_filename: 'vz-aws-rhel7' }
  - { role: apigee-opdk-yum-repository-proxy-config, when: https_proxy is defined }
  - { role: apigee-opdk-temporary-restore-targets, tags: ['restore-targets'], when: temporary_move is defined }
  - { role: apigee-opdk-setup-silent-installation-config, tags: ['apigee-silent-config'] }
