---
- hosts: localhost
  connection: local
  vars:
    image_id: 'ami-b40a36cf'
    vsad: 'D0MV'
    instance_type: m4.2xlarge
    aws_region: 'us-east-1'
    name_prefix: 'GTS-{{ vsad }}-Apigee-DC-{{ dc | default(1) }}'
    vpc_subnet_id: subnet-0756525c
    role: 'App'
    userid: 'v636401'
    nostop: ''
    owner: 'nathaly.lozano@one.verizon.com'
    portfolioVp: 'Portfolio=GTS_VP=mahmoud.elassir@one.verizon.com'
    ds_security_groups:
    - ss.nonprod.us-east-1.infrastructure.sg
    - 000-MASTER-SSH-ALL
    - 000-MASTER-HTTPS-ALL
    - 000-MASTER-HTTP-ALL
    - GTS-D0MV-Apigee-CSZK-SG
    ms_security_groups:
    - ss.nonprod.us-east-1.infrastructure.sg
    - 000-MASTER-SSH-ALL
    - 000-MASTER-HTTPS-ALL
    - 000-MASTER-HTTP-ALL
    - GTS-D0MV-Apigee-OPDK-SG
    rmp_security_groups:
    - ss.nonprod.us-east-1.infrastructure.sg
    - 000-MASTER-SSH-ALL
    - 000-MASTER-HTTPS-ALL
    - 000-MASTER-HTTP-ALL
    - GTS-D0MV-Apigee-RMP-SG
    qpid_security_groups:
    - ss.nonprod.us-east-1.infrastructure.sg
    - 000-MASTER-SSH-ALL
    - 000-MASTER-HTTPS-ALL
    - 000-MASTER-HTTP-ALL
    - GTS-D0MV-Apigee-Qpid-SG
    pg_security_groups:
    - ss.nonprod.us-east-1.infrastructure.sg
    - 000-MASTER-SSH-ALL
    - 000-MASTER-HTTPS-ALL
    - 000-MASTER-HTTP-ALL
    - GTS-D0MV-Apigee-Postgres-SG

  tasks: 
  - name: Create DS EC2 instances
    tags: ['ds']
    ec2:
      assign_public_ip: 'n'
      image: '{{ image_id }}'
      instance_type: '{{ instance_type }}'
      region: '{{ aws_region }}'
      state: present
      group: '{{ ds_security_groups }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: '{{ name_prefix }}-DS{{ item }}'
        Role: '{{ role }}'
        Vsad: '{{ vsad }}'
        Userid: '{{ userid }}'
        nostop: '{{ nostop }}'
        Owner: '{{ owner }}'
        Portfolio_VP: '{{ portfolioVp }}'
    environment:
      http_proxy: http://proxy.ebiz.verizon.com:80
      https_proxy: http://proxy.ebiz.verizon.com:80
      no_proxy: 169.254.169.254
    register: ds_instance
    with_sequence: start={{ ds_start | default(1) }} end={{ ds_end | default(3) }}

  - name: Create MS EC2 instance
    tags: ['ms']
    ec2:
      assign_public_ip: 'n'
      image: '{{ image_id }}'
      instance_type: '{{ instance_type }}'
      region: '{{ aws_region }}'
      state: present
      group: '{{ ms_security_groups }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: '{{ name_prefix }}-MS{{ item }}'
        Role: '{{ role }}'
        Vsad: '{{ vsad }}'
        Userid: '{{ userid }}'
        nostop: '{{ nostop }}'
        Owner: '{{ owner }}'
        Portfolio_VP: '{{ portfolioVp }}'
    environment:
      http_proxy: http://proxy.ebiz.verizon.com:80
      https_proxy: http://proxy.ebiz.verizon.com:80
      no_proxy: 169.254.169.254
    register: ms_instance
    with_sequence: start={{ ms_start | default(1) }} end={{ ms_end | default(1) }}

  - name: Create RMP EC2 instance
    tags: ['rmp']
    ec2:
      assign_public_ip: 'n'
      image: '{{ image_id }}'
      instance_type: '{{ instance_type }}'
      region: '{{ aws_region }}'
      state: present
      group: '{{ rmp_security_groups }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: '{{ name_prefix }}-RMP{{ item }}'
        Role: '{{ role }}'
        Vsad: '{{ vsad }}'
        Userid: '{{ userid }}'
        nostop: '{{ nostop }}'
        Owner: '{{ owner }}'
        Portfolio_VP: '{{ portfolioVp }}'
    environment:
      http_proxy: http://proxy.ebiz.verizon.com:80
      https_proxy: http://proxy.ebiz.verizon.com:80
      no_proxy: 169.254.169.254
    register: rmp_instance
    with_sequence: start={{ rpm_start | default(1) }} end={{ rmp_end | default(2) }}

  - name: Create QPID EC2 instance
    tags: ['qpid']
    ec2:
      assign_public_ip: 'n'
      image: '{{ image_id }}'
      instance_type: '{{ instance_type }}'
      region: '{{ aws_region }}'
      state: present
      group: '{{ qpid_security_groups }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: '{{ name_prefix }}-QPID{{ item }}'
        Role: '{{ role }}'
        Vsad: '{{ vsad }}'
        Userid: '{{ userid }}'
        nostop: '{{ nostop }}'
        Owner: '{{ owner }}'
        Portfolio_VP: '{{ portfolioVp }}'
    environment:
      http_proxy: http://proxy.ebiz.verizon.com:80
      https_proxy: http://proxy.ebiz.verizon.com:80
      no_proxy: 169.254.169.254
    register: qpid_instance
    with_sequence: start={{ qpid_start | default(1) }} end={{ qpid_end | default(2) }}

  - name: Create PS EC2 instance
    tags: ['pg']
    ec2:
      assign_public_ip: 'n'
      image: '{{ image_id }}'
      instance_type: '{{ instance_type }}'
      region: '{{ aws_region }}'
      state: present
      group: '{{ pg_security_groups }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: '{{ name_prefix }}-PG{{ item }}'
        Role: '{{ role }}'
        Vsad: '{{ vsad }}'
        Userid: '{{ userid }}'
        nostop: '{{ nostop }}'
        Owner: '{{ owner }}'
        Portfolio_VP: '{{ portfolioVp }}'
    environment:
      http_proxy: http://proxy.ebiz.verizon.com:80
      https_proxy: http://proxy.ebiz.verizon.com:80
      no_proxy: 169.254.169.254
    register: pg_instance
    with_sequence: start={{ pg_start | default(1) }} end={{ pg_end | default(2) }}

  - name: Verify each hosts
    include: ec2-verifications-of-hosts.yml
    loop_control:
      loop_var: result
    with_items:
    - '{{ ds_instance.results }}'
    - '{{ ms_instance.results }}'
    - '{{ rmp_instance.results }}'
    - '{{ qpid_instance.results }}'
    - '{{ pg_instance.results }}'

