---
- hosts: localhost
  connection: local
  vars:
    image_id: 'ami-b40a36cf'
    vsad: 'D0MV'
    aws_region: 'us-east-1'
    name_prefix: 'GTS-{{ vsad }}-Apigee-DC-{{ dc }}'
    vpc_subnet_id: subnet-0756525c
    role: 'App'
    userid: 'v636401'
    nostop: ''
    owner: 'nathaly.lozano@one.verizon.com'
    portfolioVp: 'Portfolio=GTS_VP=mahmoud.elassir@one.verizon.com'
    ds_security_groups:
    - ss.nonprod.us-east-1.infrastructure.sg
    - 000-MASTER-SSH-ALL
    - 000-MASTER-HTTPS-ALL
    - 000-MASTER-HTTP-ALL
    - GTS-D0MV-Apigee-CSZK-SG
    ms_security_groups:
    - ss.nonprod.us-east-1.infrastructure.sg
    - 000-MASTER-SSH-ALL
    - 000-MASTER-HTTPS-ALL
    - 000-MASTER-HTTP-ALL
    - GTS-D0MV-Apigee-OPDK-SG
    rmp_security_groups:
    - ss.nonprod.us-east-1.infrastructure.sg
    - 000-MASTER-SSH-ALL
    - 000-MASTER-HTTPS-ALL
    - 000-MASTER-HTTP-ALL
    - GTS-D0MV-Apigee-RMP-SG
    qs_security_groups:
    - ss.nonprod.us-east-1.infrastructure.sg
    - 000-MASTER-SSH-ALL
    - 000-MASTER-HTTPS-ALL
    - 000-MASTER-HTTP-ALL
    - GTS-D0MV-Apigee-Qpid-SG
    ps_security_groups:
    - ss.nonprod.us-east-1.infrastructure.sg
    - 000-MASTER-SSH-ALL
    - 000-MASTER-HTTPS-ALL
    - 000-MASTER-HTTP-ALL
    - GTS-D0MV-Apigee-Postgres-SG

  tasks: 
  - name: Create DS EC2 instances
    tags: ['ds']
    ec2:
      assign_public_ip: 'n'
      image: '{{ image_id }}'
      instance_type: m4.2xlarge
      region: '{{ aws_region }}'
      state: present
      group: '{{ ds_security_groups }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: '{{ name_prefix }}-DS{{ item }}'
        Role: '{{ role }}'
        Vsad: '{{ vsad }}'
        Userid: '{{ userid }}'
        nostop: '{{ nostop }}'
        Owner: '{{ owner }}'
        Portfolio_VP: '{{ portfolioVp }}'
    environment:
      http_proxy: http://proxy.ebiz.verizon.com:80
      https_proxy: http://proxy.ebiz.verizon.com:80
      no_proxy: 169.254.169.254
    register: ds_instance
    with_sequence: start={{ start | default(1) }} end={{ end | default(3) }}

  - name: Create MS EC2 instance
    tags: ['ms']
    ec2:
      assign_public_ip: 'n'
      image: '{{ image_id }}'
      instance_type: m4.2xlarge
      region: '{{ aws_region }}'
      state: present
      group: '{{ ms_security_groups }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: '{{ name_prefix }}-MS{{ item }}'
        Role: '{{ role }}'
        Vsad: '{{ vsad }}'
        Userid: '{{ userid }}'
        nostop: '{{ nostop }}'
        Owner: '{{ owner }}'
        Portfolio_VP: '{{ portfolioVp }}'
    environment:
      http_proxy: http://proxy.ebiz.verizon.com:80
      https_proxy: http://proxy.ebiz.verizon.com:80
      no_proxy: 169.254.169.254
    register: ds_instance
    with_sequence: start={{ start | default(1) }} end={{ end | default(1) }}

  - name: Create RMP EC2 instance
    tags: ['rmp']
    ec2:
      assign_public_ip: 'n'
      image: '{{ image_id }}'
      instance_type: m4.2xlarge
      region: '{{ aws_region }}'
      state: present
      group: '{{ rmp_security_groups }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: '{{ name_prefix }}-RMP{{ item }}'
        Role: '{{ role }}'
        Vsad: '{{ vsad }}'
        Userid: '{{ userid }}'
        nostop: '{{ nostop }}'
        Owner: '{{ owner }}'
        Portfolio_VP: '{{ portfolioVp }}'
    environment:
      http_proxy: http://proxy.ebiz.verizon.com:80
      https_proxy: http://proxy.ebiz.verizon.com:80
      no_proxy: 169.254.169.254
    register: ds_instance
    with_sequence: start={{ start | default(1) }} end={{ end | default(3) }}

  - name: Create QS EC2 instance
    tags: ['qs']
    ec2:
      assign_public_ip: 'n'
      image: '{{ image_id }}'
      instance_type: m4.2xlarge
      region: '{{ aws_region }}'
      state: present
      group: '{{ qs_security_groups }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: '{{ name_prefix }}-QS{{ item }}'
        Role: '{{ role }}'
        Vsad: '{{ vsad }}'
        Userid: '{{ userid }}'
        nostop: '{{ nostop }}'
        Owner: '{{ owner }}'
        Portfolio_VP: '{{ portfolioVp }}'
    environment:
      http_proxy: http://proxy.ebiz.verizon.com:80
      https_proxy: http://proxy.ebiz.verizon.com:80
      no_proxy: 169.254.169.254
    register: ds_instance
    with_sequence: start={{ start | default(1) }} end={{ end | default(2) }}

  - name: Create PS EC2 instance
    tags: ['ps']
    ec2:
      assign_public_ip: 'n'
      image: '{{ image_id }}'
      instance_type: m4.2xlarge
      region: '{{ aws_region }}'
      state: present
      group: '{{ ps_security_groups }}'
      vpc_subnet_id: '{{ vpc_subnet_id }}'
      instance_tags:
        Name: '{{ name_prefix }}-PS{{ item }}'
        Role: '{{ role }}'
        Vsad: '{{ vsad }}'
        Userid: '{{ userid }}'
        nostop: '{{ nostop }}'
        Owner: '{{ owner }}'
        Portfolio_VP: '{{ portfolioVp }}'
    environment:
      http_proxy: http://proxy.ebiz.verizon.com:80
      https_proxy: http://proxy.ebiz.verizon.com:80
      no_proxy: 169.254.169.254
    register: ds_instance
    with_sequence: start={{ start | default(1) }} end={{ end | default(2) }}

  - name: Wait for SSH to be ready
    wait_for_connection: 
      timeout: 600
      delay: 180

  - name: Ensure Firstboot Completion Verification
    ignore_errors: yes
    register: firstboot_result
    until: firstboot_result.matched
    retries: 1000
    delay: 360
    find:
       paths: "/var/log/"
       patterns: "firstboot_verify.log"
       contains: "Firstboot Operations Completed Successfully"

  - name: Report Firstboot Operations Success
    debug:
      msg: "Firstboot Operations Succeeded"
    when: firstboot.matched == 1

  - name: Report Firstbook Operations Failure
    fail:
      msg: "Firstboot Operations Failed"
    when: firstboot.matched != 1

  - name: Request AWS Access
    tags: ['netgroup']
    uri:
      url: https://vwebsac.verizon.com/OneAccessCloudServices/ITSecurity/AccessServices/RequestAccess 
      method: POST
      headers: 
        'Authorization': 'Basic QVBJR0VFX1VzZXI6IXZ6R0B0M3dheUAxIQ=='
        'Cache-Control': 'no-cache'
      body_format: json
      body: 
        Users: 
        - { EID: 'CM10002583' } 
        Environment: 'NONPROD'
        Hosts: 
        -  Name: "{{ instance.instances[0].private_ip | regex_replace('\\.','-') }}.ebiz.verizon.com"
        VastID: 24824
        Role: "SRVCACCT"
        OS: "linux"

  - name: Application Netgroup Verification 
    find: 
      paths: "/etc/security"
      patterns: "access-sshd.conf"
      contains: "D0MV_SRVACCOUNT_NONPROD_ONSHORE"
      size: "873"
    ignore_errors: yes
    register: app_netgroup
    until: app_netgroup.matched
    retries: 16
    delay: 30

  - name: Verify Netgroup has passed"
    debug: 
      msg: "app_netgroup verification successful"
    when: app_netgroup.matched == 1

  - name: Verify App Netgroup has failed
    fail: 
      msg: "Post Boot Process Verification Failed"
    when: app_netgroup.matched != 1


