---
- name: Configure Postgres Master on DC-2
  hosts: pgmaster
  gather_facts: no
  serial: 1
  tags: ['pgmaster']
  roles:
  - { role: apigee-opdk-setup-postgres-master }
  - { role: apigee-opdk-setup-status, tags: ['status'] }

- name: Configure Postgres Standby on DC-1
  hosts: pgstandby
  gather_facts: no
  serial: 1
  tags: ['pg', 'pgstandby']
  roles:
  - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self']  }
  - { role: apigee-opdk-setup-postgres-standby }
  - { role: apigee-opdk-setup-status, tags: ['status'] }

- name: Register Postgres on DC-2
  hosts: dc-2-pgmaster
  gather_facts: no
  serial: 1
  tags: ['pgregister']
  roles:
  - { role: apigee-opdk-setup-postgresql-add, pgmaster_group_name: 'dc-2-pgmaster', pgstandby_group_name: 'dc-2-pgstandby' }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
