---
- name: Rebuild Cassandra
  hosts: "{{ target_hosts }}"
  serial: 1
  gather_facts: no
  tags: ['ms', 'cass-rebuild']
  vars:
    opdk_region: dc-1
  roles:
  - { role: apigee-opdk-cassandra-rebuild }