---
- name: Configure Postgres Master
  hosts: "{{ pg_master_node }}"
  gather_facts: no
  serial: 1
  tags: ['pg', 'pgmaster']
  roles:
  - { role: apigee-opdk-setup-postgres-master, opdk_installation_config_file: "{{ opdk_portal_db_config_file }}" }
  - { role: apigee-opdk-setup-status, tags: ['status'] }

- name: Configure Postgres Standby
  hosts: "{{ pg_standby_node }}"
  gather_facts: no
  serial: 1
  tags: ['pg', 'pgstandby']
  roles:
  - { role: apigee-opdk-stop-components, component_name: 'apigee-postgresql' }
  - { role: apigee-opdk-setup-postgres-standby, opdk_installation_config_file: "{{ opdk_portal_db_config_file }}" }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
