---
- name: Update planet cache
  include: apigee-planet-cache.yml
  vars:
    target_hosts: planet

- name: Install and configure OS pre-requisites
  include: apigee-os-pre-requisites.yml
  vars:
    target_hosts: planet

- name: Install Apigee pre-requisites
  include: apigee-pre-requisites-bootstrap.yml
  vars:
    target_hosts: planet

- name: Install Apigee pre-requisites
  include: apigee-pre-requisites-common-install.yml
  vars:
    target_hosts: planet

- name: Configure Apigee pre-requisites
  include: apigee-configuration.yml
  vars:
    target_hosts: planet

- name: Configure Apigee pre-requisites
  include: apigee-configuration.yml
  tags: ['ds','ds-config-file']
  vars:
    target_hosts: dc-1-ds

- name: Install Cassandra & Zookeeper node
  include: install-edge-cassandra-zookeeper-component-install.yml
  tags: ['ds','ds-install', 'ds-ami']

- name: Install Cassandra & Zookeeper node
  include: install-edge-cassandra-zookeeper-component-setup.yml
  tags: ['ds','ds-setup']

- name: Configure Apigee pre-requisites
  include: apigee-configuration.yml
  tags: ['ms','ms-config-file']
  vars:
    target_hosts: dc-1-ms

- name: Install Management Server node
  include: install-edge-management-server-component-install.yml
  tags: ['ms','ms-install','ms-ami']

- name: Install Management Server node
  include: install-edge-management-server-component-setup.yml
  tags: ['ms','ms-setup']

- name: Configure Apigee pre-requisites
  include: apigee-configuration.yml
  tags: ['rmp','rmp-config-file']
  vars:
    target_hosts: dc-1-rmp

- name: Install Router & Message Processor node
  include: install-edge-rmp-component-install.yml
  tags: ['rmp','rmp-install', 'rmp-ami']

- name: Install Router & Message Processor node
  include: install-edge-rmp-component-setup.yml
  tags: ['rmp','rmp-setup']

- name: Configure Apigee pre-requisites
  include: apigee-configuration.yml
  tags: ['qs','qs-config-file']
  vars:
    target_hosts: dc-1-qpid

- name: Install Qpid node
  include: install-edge-qs-component-install.yml
  tags: ['qs','qs-install','qs-ami']

- name: Install Qpid node
  include: install-edge-qs-component-setup.yml
  tags: ['qs','qs-setup']

- name: Configure Apigee pre-requisites
  include: apigee-configuration.yml
  tags: ['ps','ps-config-file']
  vars:
    target_hosts: dc-1-pg

- name: Install Postgres node
  include: install-edge-pg-component-install.yml
  tags: ['ps','ps-install','ps-ami']

- name: Install Postgres node
  include: install-edge-pg-component-setup.yml
  tags: ['ps','ps-setup']

- name: Rolling restart of planet
  hosts: planet
  serial: 1
  tags: ['restart']
  roles:
  - apigee-opdk-stop-components
  - apigee-opdk-start-components

- name: Setup org
  include: install-edge-setup-org.yml
  tags: ['org']

- name: Validate RMP
  include: install-edge-rmp-validate.yml
  tags: ['validate-rmp']

- name: Download logs and configs
  tags: ['logs']
  include: apigee-log-config-files.yml
  vars:
    target_hosts: planet





