---
- name: Update user with root privilege
  include: configuration/update-user.yml
  vars:
    hosts: 'planet'
    user: 'root'
  tags:
  - root-user

- name: Update nodes with pre-requisites
  hosts: planet
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-setup-default-settings, tags: ['cache'] }
  - { role: apigee-opdk-setup-os-minimum, tags: ['os', 'os-pre-req'] }
  - { role: apigee-opdk-setup-selinux-disable, tags: ['os', 'os-pre-req'] }
  - { role: apigee-opdk-shutdown-iptables, tags: ['os', 'os-pre-req'] }
  - { role: apigee-opdk-setup-os-common, tags: ['os', 'os-pre-req'] }
  - { role: apigee-opdk-setup-apigee-user, tags: ['apigee-user', 'apigee-pre-req'], jdk_version: '1.8' }
  - { role: apigee-opdk-setup-os-limits, tags: ['apigee-pre-req', 'apigee-tuning'], jdk_version: '1.8' }
  - { role: apigee-opdk-setup-openjdk, tags: ['apigee-pre-req', 'openjdk'], jdk_version: '1.8' }
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-pre-req', 'apigee-bootstrap'], jdk_version: '1.8' }
  - { role: apigee-opdk-setup-silent-installation-config, tags: ['apigee-pre-req', 'apigee-silent-config'], jdk_version: '1.8' }

- name: Setup Cassandra & Zookeeper in DC-1
  include: components/opdk-install-component.yml
  vars:
    hosts: 'dc-1-ds'
    component_profile: 'ds'
  tags:
  - ds

- name: Setup Management Server on DC-1
  include: components/opdk-install-component.yml
  vars:
    hosts: 'dc-1-ms'
    component_profile: 'ms'
  tags:
  - ms

- name: Setup UI on DC-1
  include: components/opdk-install-component.yml
  vars:
    hosts: 'dc-1-ms'
    component_profile: 'ui'
  tags:
  - ui

- name: Setup RMP on DC-1
  include: components/opdk-install-component.yml
  vars:
    hosts: 'dc-1-rmp'
    component_profile: 'rmp'
  tags:
  - rmp

- name: Setup Qpid on DC-1
  include: components/opdk-install-component.yml
  vars:
    hosts: 'dc-1-qpid'
    component_profile: 'qs'
  tags:
  - qpid
  - analytics

- name: Setup Postgres Master on DC-1
  include: components/opdk-setup-postgres-common.yml
  vars:
    hosts: 'dc-1-pgmaster'
    pg_component: 'master'
  tags:
  - pg
  - pgmaster
  - analytics

- name: Setup Postgres Standby on DC-1
  include: components/opdk-setup-postgres-common.yml
  vars:
    hosts: 'dc-1-pgstandby'
    pg_component: 'standby'
  tags:
  - pg
  - pgstandby
  - analytics

- name: Setup org on DC-1
  include: configuration/opdk-setup-org.yml
  vars:
    hosts: 'dc-1-ms'
  tags:
  - org

- name: Validate RMP proxy functionality on DC-1
  include: validations/opdk-setup-validate.yml
  vars:
    hosts: 'dc-1-rmp'
  tags:
  - validation

- name: Validate internal port connectivity
  include: validations/opdk-internal-port-connectivity-validator.yml
  tags:
  - port-validator

- name: Report status for all nodes
  include: validations/opdk-setup-status.yml
  vars:
    hosts: 'planet'
  tags:
  - status

- name: Download logs and configs from DC-1-DS
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-ds
  tags:
  - logs
  - dc-1

- name: Download logs and configs from DC-1-MS
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-ms
  tags:
  - logs
  - dc-1

- name: Download logs and configs from DC-1-RMP
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-rmp
  tags:
  - logs
  - dc-1

- name: Download logs and configs from DC-1-QPID
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-qpid
  tags:
  - logs
  - dc-1
  - qpid

- name: Download logs and configs from DC-1-PGMASTER
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-pgmaster
  tags:
  - logs
  - dc-1

- name: Download logs and configs from DC-1-PGSTANDBY
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-pgstandby
  tags:
  - logs
  - dc-1


