---
- name: Update planet cache
  import_playbook: apigee-planet-cache.yml
  vars:
    target_hosts: planet

- name: Install and configure OS pre-requisites
  import_playbook: apigee-os-pre-requisites.yml
  vars:
    target_hosts: cf-mirror

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-bootstrap.yml
  vars:
    target_hosts: cf-mirror

- name: Create apigee mirror
  hosts: cf-mirror
  tags: ['mirror']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  roles:
  - { role: apigee-opdk-setup-bootstrap-create-archive, tags: ['create-archive'] }
  - { role: apigee-opdk-setup-mirror-nginx, tags: ['nginx-mirror'] }

