---
- name: Update the ansible cache
  hosts: planet
  tags: ['cache']
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings

- name: Setup OS
  include: configuration/opdk-setup-os.yml
  vars:
    hosts: 'planet'
  tags:
  - os
  - os-pre-req

- name: Update user with root privilege
  include: configuration/update-user.yml
  vars:
    hosts: 'planet'
    user: 'root'
  tags:
  - root-user

- name: Setup Edge pre-requisites
  include: components/opdk-pre-requisites.yml
  vars:
    hosts: 'planet'
    jdk_version: '1.8'
  tags:
  - apigee-pre-req

- name: Setup Cassandra & Zookeeper in DC-1
  include: components/opdk-install-component.yml
  vars:
    hosts: 'dc-1-ds'
    component_profile: 'ds'
  tags:
  - ds

- name: Setup Management Server on DC-1
  include: components/opdk-install-component.yml
  vars:
    hosts: 'dc-1-ms'
    component_profile: 'ms'
  tags:
  - ms

- name: Setup RMP on DC-1
  include: components/opdk-install-component.yml
  vars:
    hosts: 'dc-1-rmp'
    component_profile: 'rmp'
  tags:
  - rmp

- name: Setup Qpid on DC-1
  include: components/opdk-install-component.yml
  vars:
    hosts: 'dc-1-qpid'
    component_profile: 'qs'
  tags:
  - qpid
  - analytics

- name: Setup Postgres Master on DC-1
  include: components/opdk-setup-postgres-common.yml
  vars:
    hosts: 'dc-1-pgmaster'
    pg_component: 'master'
  tags:
  - pg
  - pgmaster
  - analytics

- name: Setup Postgres Standby on DC-1
  include: components/opdk-setup-postgres-common.yml
  vars:
    hosts: 'dc-1-pgstandby'
    pg_component: 'standby'
  tags:
  - pg
  - pgstandby
  - analytics

- name: Setup org on DC-1
  include: configuration/opdk-setup-org.yml
  vars:
    hosts: 'dc-1-ms'
  tags:
  - org

- name: Validate RMP proxy functionality on DC-1
  include: validations/opdk-setup-validate.yml
  vars:
    hosts: 'dc-1-rmp'
  tags:
  - validation

- name: Validate internal port connectivity
  include: validations/opdk-internal-port-connectivity-validator.yml
  tags:
  - port-validator

- name: Report status for all nodes
  include: validations/opdk-setup-status.yml
  vars:
    hosts: 'planet'
  tags:
  - status

- name: Download logs and configs from DC-1-DS
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-ds
  tags:
  - logs
  - dc-1

- name: Download logs and configs from DC-1-MS
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-ms
  tags:
  - logs
  - dc-1

- name: Download logs and configs from DC-1-RMP
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-rmp
  tags:
  - logs
  - dc-1

- name: Download logs and configs from DC-1-QPID
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-qpid
  tags:
  - logs
  - dc-1
  - qpid

- name: Download logs and configs from DC-1-PGMASTER
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-pgmaster
  tags:
  - logs
  - dc-1

- name: Download logs and configs from DC-1-PGSTANDBY
  include: validations/opdk-setup-log-files.yml
  vars:
    hosts: dc-1-pgstandby
  tags:
  - logs
  - dc-1


