---
- name: Setup Qpid on DC-1
  hosts: dc-1-qpid
  gather_facts: no
  tags: ['qpid']
  roles:
  - { role: apigee-opdk-setup-component-installer, tags: ['apigee-component', 'installer'] }
  - { role: apigee-opdk-setup-component, profile: 'qs',tags: ['apigee-component']  }
  - { role: apigee-opdk-start-components, tags: ['apigee-component'] }
  - { role: apigee-opdk-server-self, server_types: ['qs'], tags: ['self']  }
  - { role: apigee-opdk-setup-status, tags: ['status'] }

