---
- name: Configure Management Server on DC-1
  hosts: dc-1-ms
  serial: 1
  gather_facts: no
  tags: ['ms']
  roles:
  - { role: apigee-opdk-setup-component, profile: 'ms',tags: ['apigee-component']  }
  - { role: apigee-opdk-setup-component, profile: 'ui',tags: ['apigee-component']  }
  - { role: apigee-opdk-server-self, server_types: ['ms'], tags: ['self'] }
  - { role: apigee-opdk-setup-status, tags: ['status'] }