---
- name: Validate RMP proxy functionality on DC-1
  hosts: "{{ target_hosts }}"
  serial: 1
  gather_facts: no
  tags: ['validate']
  roles:
  - { role: apigee-opdk-setup-validate }
  - { role: apigee-opdk-setup-validate-cleanup, tags: ['validate-rmp-cleanup'] }
