---
- name: Update planet cache
  include: apigee-planet-cache.yml
  vars:
    target_hosts: planet

- name: Install and configure OS pre-requisites
  include: apigee-os-pre-requisites.yml
  tags: ['os-ami']
  vars:
    target_hosts: planet

- name: Install Apigee pre-requisites
  include: apigee-pre-requisites-bootstrap.yml
  tags: ['bootstrap','ami']
  vars:
    target_hosts: planet

- name: Install Apigee pre-requisites
  include: apigee-pre-requisites-common-install.yml
  tags: ['common','ami']
  vars:
    target_hosts: planet

- name: Configure Cassandra & Zookeeper node
  include: apigee-configuration.yml
  tags: ['ds','ds-config-file','config']
  vars:
    target_hosts: dc-1-ds,dc-2-ds

- name: Apply configuration to Cassandra & Zookeeper node
  include: install-edge-cassandra-zookeeper-component-setup.yml
  tags: ['ds','ds-apply-config','config']
  vars:
    target_hosts: dc-1-ds

- name: Configure MS node
  include: apigee-configuration.yml
  tags: ['ms','ms-config-file','config']
  vars:
    target_hosts: dc-1-ms

- name: Apply configuration to Management Server node
  include: install-edge-management-server-component-setup.yml
  tags: ['ms','ms-apply-config','config']

- name: Configure RMP node
  include: apigee-configuration.yml
  tags: ['rmp','rmp-config-file','config']
  vars:
    target_hosts: dc-1-rmp

- name: Apply configuration to Router & Message Processor node
  include: install-edge-rmp-component-setup.yml
  tags: ['rmp','rmp-apply-config','config']

- name: Configure Qpid node
  include: apigee-configuration.yml
  tags: ['qs','qs-config-file','config']
  vars:
    target_hosts: dc-1-qpid

- name: Apply configuration to Qpid node
  include: install-edge-qs-component-setup.yml
  tags: ['qs','qs-apply-config','config']

- name: Configure Apigee pre-requisites
  include: apigee-configuration.yml
  tags: ['ps','ps-config-file','config']
  vars:
    target_hosts: dc-1-pg

- name: Install Postgres node
  include: install-edge-pg-component-setup.yml
  tags: ['ps','ps-apply-config','config']

- name: Setup org
  include: install-edge-setup-org.yml
  tags: ['org']

- name: Rolling restart of planet
  hosts: planet
  serial: 1
  tags: ['restart']
  roles:
  - apigee-opdk-stop-components
  - apigee-opdk-start-components

- name: Validate RMP
  include: install-edge-rmp-validate.yml
  tags: ['validate-rmp']

#- name: Download logs and configs
#  tags: ['logs']
#  include: apigee-log-config-files.yml
#  vars:
#    target_hosts: planet





