---
- name: Update planet cache
  include: apigee-planet-cache.yml
  vars:
    target_hosts: planet

- name: Install and configure OS pre-requisites
  include: apigee-os-pre-requisites.yml
  vars:
    target_hosts: planet

- name: Install Apigee pre-requisites
  include: apigee-pre-requisites.yml
  vars:
    target_hosts: planet

- name: Create apigee mirror
  hosts: mirror
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-setup-bootstrap-create-archive, tags: ['create-archive'] }
  - { role: apigee-opdk-setup-bootstrap-download-archive, tags: ['download-archive'] }

