---
- name: Update planet cache
  import_playbook: apigee-planet-cache.yml
  vars:
    target_hosts: planet,cfmirror

- name: Install and configure OS pre-requisites for mirror
  hosts: cfmirror
  gather_facts: no
  tags: ['os-pre-req']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  roles:
  - { role: apigee-opdk-setup-os-epel, tags: ['epel'] }
  - { role: apigee-opdk-setup-os-minimum, tags: ['os-minimum'] }
  - { role: apigee-opdk-setup-os-limits, tags: ['apigee-tuning'] }
  - { role: apigee-opdk-setup-selinux-disable, tags: ['selinux'] }
  - { role: apigee-opdk-shutdown-iptables, tags: ['iptables'] }
  - { role: apigee-server-restart, tags: ['restart-server'], when: (selinux_disabled.changed is defined and selinux_disabled.changed) or (iptables_disabled is defined and not iptables_disabled) or (force_restart is defined and force_restart)  }
  - { role: apigee-opdk-setup-os-common, tags: ['os-common'] }
  - { role: apigee-opdk-setup-openjdk, tags: ['openjdk'], jdk_version: '1.8' }

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-bootstrap.yml
  vars:
    target_hosts: cfmirror

- name: Create apigee mirror
  hosts: cfmirror
  tags: ['create']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  roles:
  - { role: apigee-opdk-setup-bootstrap-create-archive, tags: ['create-archive'] }

- name: Download apigee mirror
  hosts: cfmirror
  tags: ['download']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  roles:
  - { role: apigee-opdk-setup-bootstrap-download-archive, tags: ['download-archive'] }
  - { role: apigee-opdk-setup-mirror-nginx, tags: ['nginx-mirror'] }

- name: Upload apigee mirror
  hosts: cfmirror
  tags: ['upload']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  roles:
  - { role: apigee-opdk-setup-bootstrap-upload-archive, tags: ['upload-archive'] }

- name: Nginx apigee mirror
  hosts: cfmirror
  tags: ['download']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  roles:
  - { role: apigee-opdk-setup-mirror-nginx, tags: ['nginx-mirror'] }
