---
- name: Setup RMP on dc-1
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['rmp']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-component, profile: 'mo',tags: ['apigee-component']  }
  - { role: apigee-opdk-start-components, tags: ['apigee-component'] }
  - { role: apigee-opdk-server-self, server_types: ['ms'], tags: ['self'] }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
