---
- name: Configure Cassandra & Zookeeper in DC-1
  hosts: "{{ target_hosts }}"
  gather_facts: no
  serial: 1
  max_fail_percentage: 33
  tags: ['ds']
  roles:
  - { role: apigee-opdk-setup-component, profile: 'ds', tags: ['apigee-setup'] }
  - { role: apigee-opdk-start-components, tags: ['apigee-component'] }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
