---
- name: Update planet cache
  include: apigee-planet-cache.yml
  vars:
    target_hosts: planet

- name: Install and configure OS pre-requisites
  include: apigee-os-pre-requisites.yml
  vars:
    target_hosts: planet

- name: Install Apigee pre-requisites
  include: apigee-pre-requisites.yml
  vars:
    target_hosts: planet

- name: Configure Apigee pre-requisites
  include: apigee-configuration.yml
  vars:
    target_hosts: planet

- name: Install and configure Apigee Edge AIO
  hosts: planet
  gather_facts: no
  tags: ['aio']
  serial: 1
  vars:
    yum_manual_os_packages:
    - openldap-servers
  roles:
  - { role: apigee-opdk-setup-component, profile: 'aio', tags: ['aio']}

- name: Setup org
  include: install-edge-setup-org.yml
  tags: ['org']

- name: Validate RMP
  include: install-edge-rmp-validate.yml
  tags: ['validate-rmp']

- name: Download logs and configs
  tags: ['logs']
  include: apigee-log-config-files.yml
  vars:
    target_hosts: planet





