---
- name: Update planet cache
  include: apigee-planet-cache.yml

- name: Install and configure OS pre-requisites
  include: apigee-os-pre-requisites.yml

- name: Install and configure Apigee pre-requisites
  include: apigee-pre-requisites.yml

- name: Install and configure Apigee Edge AIO
  hosts: planet
  gather_facts: no
  serial: 1
  roles:
  - { role: apigee-opdk-temporary-remove-targets, tags: ['remove-targets', 'apigee-component', 'installer'], when: temporary_move is defined }
  - { role: apigee-opdk-setup-component-installer, tags: ['apigee-component', 'installer'] }
  - { role: apigee-opdk-temporary-restore-targets, tags: ['restore-targets', 'apigee-component', 'installer'], when: temporary_move is defined }
  - { role: apigee-opdk-temporary-remove-targets, tags: ['remove-targets', 'apigee-component'], when: temporary_move is defined }
  - { role: apigee-opdk-setup-component, profile: 'aio', tags: ['apigee-component'] }
  - { role: apigee-opdk-temporary-restore-targets, tags: ['restore-targets', 'apigee-component'], when: temporary_move is defined }
  - { role: apigee-opdk-start-components, tags: ['start-component'] }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
  - { role: apigee-opdk-setup-org-config, tags: ['org'] }
  - { role: apigee-opdk-setup-org, tags: ['org'] }
  - { role: apigee-opdk-server-self, server_types: ['mp'] }
  - { role: apigee-opdk-setup-validate, tags: ['validate'] }
  - { role: apigee-opdk-setup-validate-cleanup, tags: ['validate','validate-cleanup'] }

- name: Download logs and configs
  tags: ['logs']
  include: apigee-log-config-files.yml
  vars:
    hosts: planet





