---
- name: Setup Monetization on dc-1
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['mo']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-provisioning, provisioning_action: 'enable-monetization', provisioning_config_file: '{{ opdk_installation_config_file }}'}

