---
- name: Update planet cache
  include: apigee-planet-cache.yml
  vars:
    target_hosts: planet

- name: Install and configure OS pre-requisites
  include: apigee-os-pre-requisites.yml
  vars:
    target_hosts: planet

- name: Install Apigee pre-requisites
  include: apigee-pre-requisites.yml
  vars:
    target_hosts: planet

- name: Configure Apigee pre-requisites
  include: apigee-configuration.yml
  vars:
    target_hosts: planet

- name: Install and configure Apigee Edge AIO
  hosts: planet
  gather_facts: no
  tags: ['aio']
  serial: 1
  vars:
    yum_manual_os_packages:
    - openldap-servers
  roles:
  - { role: apigee-opdk-setup-component-installer, tags: ['apigee-component', 'installer'] }
  - { role: apigee-opdk-setup-component, profile: 'aio', tags: ['apigee-component']}
  - { role: apigee-opdk-start-components, tags: ['start-component', 'apigee-component'] }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
  - { role: apigee-opdk-setup-org-config, tags: ['org'] }
  - { role: apigee-opdk-setup-org, tags: ['org'] }
  - { role: apigee-opdk-server-self, server_types: ['mp'] }
  - { role: apigee-opdk-setup-validate, tags: ['validate'] }
  - { role: apigee-opdk-setup-validate-cleanup, tags: ['validate','validate-cleanup'] }

- name: Install Cassandra & Zookeeper node
  include: install-edge-cassandra-zookeeper-node.yml
  tags: ['ds']

- name: Install Management Server node
  include: install-edge-management-server-node.yml
  tags: ['ms']

- name: Install Router & Message Processor node
  include: install-rmp-node.yml
  tags: ['rmp']

- name: Install Qpid node
  include: install-edge-qs-node.yml
  tags: ['qs']

- name: Install Postgres node
  include: install-edge-pgmaster-node.yml
  tags: ['ps']

- name: Setup org
  include: install-edge-setup-org.yml
  tags: ['org']

- name: Download logs and configs
  tags: ['logs']
  include: apigee-log-config-files.yml
  vars:
    target_hosts: planet





