---
- name: Configure Postgres Standby on DC-1
  hosts: pgstandby
  gather_facts: no
  serial: 1
  tags: ['pg', 'pgstandby']
  roles:
  - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self']  }
  - { role: apigee-opdk-setup-postgres-standby }
  - { role: apigee-opdk-setup-status, tags: ['status'] }

