---
- name: Update planet cache
  import_playbook: apigee-planet-cache.yml
  vars:
    target_hosts: planet

- name: Install and configure OS pre-requisites
  import_playbook: apigee-os-pre-requisites.yml
  tags: ['os']
  vars:
    target_hosts: planet

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-bootstrap.yml
  tags: ['bootstrap']
  vars:
    target_hosts: planet

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-common-install.yml
  tags: ['common']
  vars:
    target_hosts: planet

- name: Configure Cassandra & Zookeeper node
  import_playbook: apigee-configuration.yml
  tags: ['ds','ds-config']
  vars:
    target_hosts: ds

- name: Apply configuration to Cassandra & Zookeeper node
  import_playbook: install-edge-cassandra-zookeeper-component-setup.yml
  tags: ['ds','ds-setup']
  vars:
    target_hosts: ds

- name: Configure MS node
  import_playbook: apigee-configuration.yml
  tags: ['ms','ms-config']
  vars:
    target_hosts: ms

- name: Apply configuration to Management Server node
  import_playbook: install-edge-management-server-component-setup.yml
  tags: ['ms','ms-setup']
  vars:
    target_hosts: ms

- name: Configure RMP node
  import_playbook: apigee-configuration.yml
  tags: ['rmp','rmp-config']
  vars:
    target_hosts: rmp

- name: Apply configuration to Router & Message Processor node
  import_playbook: install-edge-rmp-component-setup.yml
  tags: ['rmp','rmp-setup']
  vars:
    target_hosts: rmp

- name: Configure Qpid node
  import_playbook: apigee-configuration.yml
  tags: ['qpid','qpid-config']
  vars:
    target_hosts: qpid

- name: Apply configuration to Qpid node
  import_playbook: install-edge-qpid-component-setup.yml
  tags: ['qpid','qpid-setup']
  vars:
    target_hosts: qpid

- name: Configure Apigee pre-requisites
  import_playbook: apigee-configuration.yml
  tags: ['pg','pg-config']
  vars:
    target_hosts: pg

- name: Install Postgres node
  import_playbook: install-edge-pg-component-setup.yml
  tags: ['pg','pg-setup']
  vars:
    target_hosts: pg

- name: Install Postgres node
  import_playbook: edge-expansion-pgmaster-pgstandby-node-config.yml
  tags: ['pg','pg-expand']

- name: Setup org
  import_playbook: install-edge-setup-org.yml
  tags: ['org']
  vars:
    target_hosts: ms

- name: Rolling restart of dc-1
  hosts: planet
  serial: 1
  tags: ['restart']
  roles:
  - apigee-opdk-stop-components
  - apigee-opdk-start-components

- name: Validate RMP
  import_playbook: install-edge-rmp-validate.yml
  tags: ['validate-rmp']
  vars:
    target_hosts: rmp

- name: Download logs and configs
  tags: ['logs']
  import_playbook: apigee-log-config-files.yml
  vars:
    target_hosts: planet
