---
- name: Configure Cassandra & Zookeeper in DC-1
  hosts: dc-1-ds
  gather_facts: no
  serial: 1
  tags: ['ds']
  roles:
  - { role: apigee-opdk-setup-component-install, component: 'apigee-cassandra', tags: ['apigee-component'] }
  - { role: apigee-opdk-setup-component-install, component: 'apigee-zookeeper', tags: ['apigee-component'] }
