---
- name: Install Postgres on DC-1
  hosts: dc-1-pg
  gather_facts: no
  serial: 1
  tags: ['pg', 'pgcommon']
  roles:
  - { role: apigee-opdk-setup-component-installer, tags: ['apigee-component', 'installer'] }
  - { role: apigee-opdk-setup-component, profile: 'ps', tags: ['apigee-component'] }
  - { role: apigee-opdk-start-components, tags: ['apigee-component'] }

- name: Configure Postgres Master on DC-1
  hosts: dc-1-pgmaster
  gather_facts: no
  serial: 1
  tags: ['pg','pgmaster']
  roles:
  - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self']  }
  - { role: apigee-opdk-setup-postgres-master }
  - { role: apigee-opdk-setup-status, tags: ['status'] }

- name: Configure Postgres Standby on DC-1
  hosts: dc-1-pgstandby
  gather_facts: no
  serial: 1
  tags: ['pg', 'pgstandby']
  roles:
  - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self']  }
  - { role: apigee-opdk-setup-postgres-standby }
  - { role: apigee-opdk-setup-status, tags: ['status'] }

