---
- name: Added available space to instance
  hosts: planet
  gather_facts: no


  tasks:
  - name: Install gdisk
    yum:
      name: gdisk
      state: present

  - name: Create partition from available space
    shell: >
      gdisk /dev/xvga << EOF
      n
      \n
      \n
      \n
      \n
      w
      EOF

 - name: Re-read partition table
   shell: partprobe

  - name: Create physical volume and extend volume group from partition
    lvg:
      pvs: /dev/xvga
      state: present
      vg: vgroot

  - name: Extend local volume from added physical volume
    lvol:
      state: present
      vg: vgroot
      lv: /dev/mapper/vgroot-lvvar
      pvs: /dev/xvga
      size: +10G



