---
- name: Update individual cache value
  hosts: "{{ target_hosts }}"
  gather_facts: no
  roles:
  - { role: apigee-opdk-modules}
  tasks:
  - name: Update individual cache value
    cache:
      key: "{{ cache_attr_name }}"
      value: "{{ cache_attr_value }}"

