---
- hosts: '{{ hosts }}'
  vars_files:
  - ~/.apigee/credentials.yml
  serial: 1
  roles:
  - apigee-opdk-setup-default-settings
  - { role: apigee-opdk-server-self, server_type: 'mp'}
  - apigee-opdk-setup-validate
  tags:
  - validate

- hosts: '{{ hosts }}'
  vars_files:
  - ~/.apigee/credentials.yml
  serial: 1
  roles:
  - apigee-opdk-setup-validate-cleanup
  tags:
  - validate
  - validate-cleanup
