---
- hosts: '{{ hosts }}'
  serial: 1
  roles:
  - { role: apigee-opdk-enable-swap, tags: ['os-pre-req'] }
  - { role: apigee-opdk-setup-os-postgres, tags: ['os-pre-req'] }
  - { role: apigee-opdk-setup-postgres-config, tags: ['apigee-pre-req'] }
  - { role: apigee-opdk-setup-component-installer, tags: ['apigee-component'] }
  - { role: apigee-opdk-setup-component, tags: ['apigee-component'], profile: 'ps' }

- include: 'opdk-setup-postgres-master.yml'
  when: pg_component is defined and pg_component == 'master'
  tags:
  - apigee-component

- include: 'opdk-setup-postgres-standby.yml'
  when: pg_component is defined and pg_component == 'standby'
  tags:
  - apigee-component
