---
- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-enable-swap
  - apigee-opdk-setup-default-settings
  - apigee-opdk-setup-os-postgres
  tags:
  - os-pre-req

- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings
  - apigee-opdk-setup-postgres-config
  tags:
  - apigee-pre-req

- include: opdk-install-component.yml
  vars:
    hosts: '{{ hosts }}'
    component_profile: 'ps'
  tags:
  - apigee-component

- include: 'opdk-setup-postgres-{{ pg_component }}.yml'
  when: pg_component is defined
  tags:
  - apigee-component
